### PR TITLE
Added method to add file in subfolder to asicE container

### PR DESCRIPTION
**Pull request by AElvik**
This method gives the option to add a file to a folder inside the ASiCe archive. This is required by the party we are trying to integrate with.

I'm not sure if this is the best solution for this problem. One option would be to add a optional flag to the AddFile method, and exclude the Path.GetFileName method if this is set. Another would be to open up access to the asiceArchived, so AddEntry could be used directly.

I'm not sure if creating files in sub folders is allowed by the specification..

### CODE REVIEW

**Comment by zapodot** [comment]
Thanks @AElvik ! Could you add a test that shows what differs this from the existing method?

**Comment by zapodot** [comment]
According to the spec at https://www.etsi.org/deliver/etsi_ts/102900_102999/102918/01.03.01_60/ts_102918v010301p.pdf you are free to add subfolders to the asci-e package. Need a test before we can approve your change.

**Comment by AElvik** [comment]
Added a test for this method. I'm not sure if this is the best way to add this functionality, but it solves my problem.

**Comment by nickun** [comment]
This change should be made for **DigestVerifier** to work correctly.
```diff
 KS.Fiks.ASiC-E/Model/AsiceReadEntry.cs | 2 +-
 1 file changed, 1 insertion(+), 1 deletion(-)

diff --git a/KS.Fiks.ASiC-E/Model/AsiceReadEntry.cs b/KS.Fiks.ASiC-E/Model/AsiceReadEntry.cs
index 843ef32..06e58ae 100644
--- a/KS.Fiks.ASiC-E/Model/AsiceReadEntry.cs
+++ b/KS.Fiks.ASiC-E/Model/AsiceReadEntry.cs
@@ -20,7 +20,7 @@ namespace KS.Fiks.ASiC_E.Model
             this._digestReceiver = digestReceiver;
         }
 
-        public string FileName => _zipArchiveEntry.Name;
+        public string FileName => _zipArchiveEntry.FullName;
 
         public Stream OpenStream()
         {
```

**Comment by nickun** [comment]
Consider this solution instead of adding a new method.
This is a more robust solution imho :)

```diff
 KS.Fiks.ASiC-E/AsiceBuilder.cs | 11 ++++++++++-
 1 file changed, 10 insertions(+), 1 deletion(-)

diff --git a/KS.Fiks.ASiC-E/AsiceBuilder.cs b/KS.Fiks.ASiC-E/AsiceBuilder.cs
index 14cef92..dd833ff 100644
--- a/KS.Fiks.ASiC-E/AsiceBuilder.cs
+++ b/KS.Fiks.ASiC-E/AsiceBuilder.cs
@@ -1,5 +1,6 @@
 using System;
 using System.IO;
+using System.Linq;
 using System.Xml;
 using KS.Fiks.ASiC_E.Crypto;
 using KS.Fiks.ASiC_E.Manifest;
@@ -63,7 +64,15 @@ namespace KS.Fiks.ASiC_E
 
         public IAsiceBuilder<AsiceArchive> AddFile(Stream stream, string filename, MimeType mimeType)
         {
-            this.asiceArchive.AddEntry(stream, new FileRef(Path.GetFileName(filename), mimeType));
+            string newFileName = Path.GetFileName(filename);
+            string directory = Path.GetDirectoryName(filename) ?? string.Empty;
+            directory = directory.Split(Path.DirectorySeparatorChar, Path.AltDirectorySeparatorChar).LastOrDefault() ?? string.Empty;
+            if (!string.IsNullOrWhiteSpace(directory))
+            {
+                newFileName = string.Concat(directory, "/", newFileName);
+            }
+
+            this.asiceArchive.AddEntry(stream, new FileRef(newFileName, mimeType));
             return this;
         }
 
```

**Comment by UweThomas** [comment]
Is there any possibility to get this into the main branch / nuget package? 
We plan to use ASiC-E for an upcomming standard for singinng firmware packages but without support for folders this library is not usable.

**Comment by jarleborsheim** [comment]
@UweThomas We are looking into this now. We are sorry that this has taken so long

**Review by jarleborsheim — APPROVED** [review]
LGTM. Great work! And sorry it took so long :)

**Pull request merged**
